spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

---

spring:
  profiles: dev
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.170:8761/eureka/

---

spring:
  profiles: test